name: Run Tests

on:
  push:
    branches:
      - master
      - '!release-do-not-use'
  pull_request:

permissions:
  contents: write

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm i
      - run: npm run unit

  release:
    if: github.repository_owner == 'BitGo' && github.event_name == 'push' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs:
      - unit
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: ./node_modules/.bin/semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
