name: Run Tests

on:
  push:
    branches:
      - master
      - '!release-do-not-use'
  pull_request:

permissions:
  contents: write

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm i
      - run: npm run unit

  release:
    if: github.repository_owner == 'BitGo' && github.event_name == 'push' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs:
      - unit
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: ./node_modules/.bin/semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
